### ISSUE TITLE
Serialize Activity and Stats

### ISSUE THREAD

**Issue by JonathanFrederick** [The-Breakfast-Club/Stats_API#7]
Add serializers, ViewSets, and routers for Activity and Stats

**Comment by kasalak** [comment]
Look at TODOMVC project for inspiration on urls.py, views.py, serializers.py and install things from requirements.txt

**Comment by kasalak** [comment]
Installed modules from requirement.txt

**Comment by kasalak** [comment]
Added a User Serializer class.
